/** Static vehicle reference data for the no-VIN entry path. */

export const DEFAULT_MAKE = "Mercedes-Benz";

export const MAKES = [
  "Mercedes-Benz",
  "Mercedes-AMG",
  "Mercedes-Maybach",
  "Smart",
  "Sprinter",
  "BMW",
  "Audi",
  "Lexus",
  "Porsche",
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Tesla",
  "Other",
] as const;

/** Common Mercedes-Benz models on a US dealer lot (sales + service loaners). */
export const MERCEDES_MODELS = [
  "A 220",
  "CLA 250",
  "CLA 35 AMG",
  "CLA 45 AMG",
  "C 300",
  "C 43 AMG",
  "C 63 AMG",
  "E 350",
  "E 450",
  "E 53 AMG",
  "E 63 AMG",
  "S 500",
  "S 580",
  "S 63 AMG",
  "Maybach S 580",
  "Maybach S 680",
  "CLE 300",
  "CLE 450",
  "CLS 450",
  "AMG GT",
  "AMG GT 43",
  "AMG GT 53",
  "AMG GT 63",
  "SL 55 AMG",
  "SL 63 AMG",
  "GLA 250",
  "GLB 250",
  "GLC 300",
  "GLC 300 Coupe",
  "GLC 43 AMG",
  "GLE 350",
  "GLE 450",
  "GLE 450e",
  "GLE 53 AMG",
  "GLE 63 AMG",
  "GLS 450",
  "GLS 580",
  "Maybach GLS 600",
  "G 550",
  "G 63 AMG",
  "EQB 250",
  "EQB 300",
  "EQE 350",
  "EQE 500",
  "EQE SUV",
  "EQS 450",
  "EQS 580",
  "EQS SUV",
  "Sprinter 2500",
  "Sprinter 3500",
  "Metris",
] as const;

export const COLORS = [
  "Black",
  "Obsidian Black",
  "Polar White",
  "Selenite Grey",
  "Graphite Grey",
  "Iridium Silver",
  "High-Tech Silver",
  "Mojave Silver",
  "Nautical Blue",
  "Spectral Blue",
  "Sodalite Blue",
  "Cardinal Red",
  "Patagonia Red",
  "Emerald Green",
  "Cirrus Silver",
  "Other",
] as const;

export function yearOptions(span = 15): number[] {
  const now = new Date().getFullYear() + 1; // next model year is on lots by fall
  return Array.from({ length: span + 1 }, (_, i) => now - i);
}
